<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:com.corticon.rulesemf.canonicalvocabularymodel="http:///com/corticon/rulesemf/canonicalvocabularymodel.ecore" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="root" nsURI="http://root/1.0" nsPrefix="root">
  <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
    <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:RootExtension" majorVersionNumber="5" minorVersionNumber="7" majorServiceNumber="2" buildNumber="8015" updateStamp="_zSPHkDnsEemM7o5GC87i7Q" externalChecksum="7824986:507989954" customDataTypeDisplayCount="50">
      <languageCode>de_DE</languageCode>
      <languageCode>ja_JP</languageCode>
      <languageCode>nl_NL</languageCode>
      <languageCode>fi_FI</languageCode>
      <languageCode>sk_SK</languageCode>
      <languageCode>pl_PL</languageCode>
      <languageCode>pt_BR</languageCode>
      <languageCode>zh_CN</languageCode>
      <languageCode>fr_FR</languageCode>
      <languageCode>it_IT</languageCode>
      <languageCode>en_US</languageCode>
      <languageCode>hu_HU</languageCode>
      <languageCode>ru_RU</languageCode>
      <languageCode>cs_CZ</languageCode>
      <languageCode>es_ES</languageCode>
      <databaseAccess databasePropertyDisplayCount="50"/>
      <customDataTypeList guid="7eaee7e2-021a-11dd-76ee-0016e677cf72" enumerationDisplayCount="50" eDataType="#//type">
        <dataTypeName manuallyCreated="true" value="type"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration manuallyCreated="true" value="true"/>
        <enumerationElements guid="7e88e951-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="Small_car"/>
          <value manuallyCreated="true" value="'Small_car'"/>
        </enumerationElements>
        <enumerationElements guid="7e4fb0e0-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="Convertible"/>
          <value manuallyCreated="true" value="'Convertible'"/>
        </enumerationElements>
        <enumerationElements guid="7e998b23-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="Van"/>
          <value manuallyCreated="true" value="'Van'"/>
        </enumerationElements>
        <enumerationElements guid="7eb3c9e3-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="Combi"/>
          <value manuallyCreated="true" value="'Combi'"/>
        </enumerationElements>
        <enumerationElements guid="7e69efa0-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="Middle_class_car"/>
          <value manuallyCreated="true" value="'Middle_class_car'"/>
        </enumerationElements>
        <enumerationElements guid="7ec1fab3-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="Limousine"/>
          <value manuallyCreated="true" value="'Limousine'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList guid="7ec6b5a3-021a-11dd-76ee-0016e677cf72" enumerationDisplayCount="50" eDataType="#//company_size">
        <dataTypeName manuallyCreated="true" value="company_size"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration manuallyCreated="true" value="true"/>
        <enumerationElements guid="7e971a22-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="big"/>
          <value manuallyCreated="true" value="'big'"/>
        </enumerationElements>
        <enumerationElements guid="7ebfb0c1-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="medium"/>
          <value manuallyCreated="true" value="'medium'"/>
        </enumerationElements>
        <enumerationElements guid="7e6eaa91-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="small"/>
          <value manuallyCreated="true" value="'small'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList guid="7ea30103-021a-11dd-76ee-0016e677cf72" enumerationDisplayCount="50" eDataType="#//company_address">
        <dataTypeName manuallyCreated="true" value="company_address"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration manuallyCreated="true" value="true"/>
        <enumerationElements guid="7e81bd63-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="Germany"/>
          <value manuallyCreated="true" value="'Germany'"/>
        </enumerationElements>
        <enumerationElements guid="7e9bd514-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="EU"/>
          <value manuallyCreated="true" value="'EU'"/>
        </enumerationElements>
        <enumerationElements guid="7ec926a3-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="others"/>
          <value manuallyCreated="true" value="'other'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList guid="7e5b97c1-021a-11dd-76ee-0016e677cf72" enumerationDisplayCount="50" eDataType="#//business_register">
        <dataTypeName manuallyCreated="true" value="business_register"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration manuallyCreated="true" value="true"/>
        <enumerationElements guid="7eaa2cf0-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="negative"/>
          <value manuallyCreated="true" value="'negative'"/>
        </enumerationElements>
        <enumerationElements guid="7ea0b711-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="positive"/>
          <value manuallyCreated="true" value="'positive'"/>
        </enumerationElements>
        <enumerationElements guid="7e8fee31-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="very_negative"/>
          <value manuallyCreated="true" value="'very_negative'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList guid="7ec6b5a0-021a-11dd-76ee-0016e677cf72" enumerationDisplayCount="50" eDataType="#//form_of_business">
        <dataTypeName manuallyCreated="true" value="form_of_business"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration manuallyCreated="true" value="true"/>
        <enumerationElements guid="7e5926c0-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="public_company"/>
          <value manuallyCreated="true" value="'public_company'"/>
        </enumerationElements>
        <enumerationElements guid="7ebd3fc1-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="Sole_proprietorship"/>
          <value manuallyCreated="true" value="'Sole proprietorship'"/>
        </enumerationElements>
        <enumerationElements guid="7e94d032-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="others"/>
          <value manuallyCreated="true" value="'other'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList guid="7e8b3341-021a-11dd-76ee-0016e677cf72" enumerationDisplayCount="50" eDataType="#//title">
        <dataTypeName manuallyCreated="true" value="title"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration manuallyCreated="true" value="true"/>
        <enumerationElements guid="7e867851-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="Mr_"/>
          <value manuallyCreated="true" value="'Mr.'"/>
        </enumerationElements>
        <enumerationElements guid="7ec1fab0-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="Mrs_"/>
          <value manuallyCreated="true" value="'Mrs.'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList guid="7e7cdb60-021a-11dd-76ee-0016e677cf72" enumerationDisplayCount="50" eDataType="#//credit_provision">
        <dataTypeName manuallyCreated="true" value="credit_provision"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration manuallyCreated="true" value="true"/>
        <enumerationElements guid="7e7f4c62-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="approved"/>
          <value manuallyCreated="true" value="'approved'"/>
        </enumerationElements>
        <enumerationElements guid="7e9e4610-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="rejected"/>
          <value manuallyCreated="true" value="'rejected'"/>
        </enumerationElements>
        <enumerationElements guid="7e8da442-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="scrutinize"/>
          <value manuallyCreated="true" value="'scrutinize'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList guid="7e7cdb61-021a-11dd-76ee-0016e677cf72" enumerationDisplayCount="50" eDataType="#//job_category">
        <dataTypeName manuallyCreated="true" value="job_category"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration manuallyCreated="true" value="true"/>
        <enumerationElements guid="7ebd3fc0-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="Public_servant"/>
          <value manuallyCreated="true" value="'Public_servant'"/>
        </enumerationElements>
        <enumerationElements guid="7eb884d0-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="Independant"/>
          <value manuallyCreated="true" value="'Independant'"/>
        </enumerationElements>
        <enumerationElements guid="7ec46bb4-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="Freelancer"/>
          <value manuallyCreated="true" value="'Freelancer'"/>
        </enumerationElements>
        <enumerationElements guid="7ebfb0c4-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="Unemployes"/>
          <value manuallyCreated="true" value="'Unemployes'"/>
        </enumerationElements>
        <enumerationElements guid="7ea57203-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="Houswife_man"/>
          <value manuallyCreated="true" value="'Houswife_man'"/>
        </enumerationElements>
        <enumerationElements guid="7eaa2cf2-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="Pupil"/>
          <value manuallyCreated="true" value="'Pupil'"/>
        </enumerationElements>
        <enumerationElements guid="7eaee7e1-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="Trainee"/>
          <value manuallyCreated="true" value="'Trainee'"/>
        </enumerationElements>
        <enumerationElements guid="7e69efa1-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="Student"/>
          <value manuallyCreated="true" value="'Student'"/>
        </enumerationElements>
        <enumerationElements guid="7e8fee30-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="Worker"/>
          <value manuallyCreated="true" value="'Worker'"/>
        </enumerationElements>
        <enumerationElements guid="7e81bd62-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="Employee"/>
          <value manuallyCreated="true" value="'Employee'"/>
        </enumerationElements>
        <enumerationElements guid="7eb613d2-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="Pensioner"/>
          <value manuallyCreated="true" value="'Pensioner'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList guid="7ec1fab2-021a-11dd-76ee-0016e677cf72" enumerationDisplayCount="50" eDataType="#//marital_status">
        <dataTypeName manuallyCreated="true" value="marital_status"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration manuallyCreated="true" value="true"/>
        <enumerationElements guid="7eb884d1-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="married"/>
          <value manuallyCreated="true" value="'married'"/>
        </enumerationElements>
        <enumerationElements guid="7e9bd512-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="single"/>
          <value manuallyCreated="true" value="'single'"/>
        </enumerationElements>
        <enumerationElements guid="7ebfb0c3-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="spouse"/>
          <value manuallyCreated="true" value="'spouse'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList guid="7e9e4611-021a-11dd-76ee-0016e677cf72" enumerationDisplayCount="50" eDataType="#//customer_rating">
        <dataTypeName manuallyCreated="true" value="customer_rating"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration manuallyCreated="true" value="true"/>
        <enumerationElements guid="7eac9df0-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="positive"/>
          <value manuallyCreated="true" value="'positive'"/>
        </enumerationElements>
        <enumerationElements guid="7ea30101-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="neutral"/>
          <value manuallyCreated="true" value="'neutral'"/>
        </enumerationElements>
        <enumerationElements guid="7e840752-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="negative"/>
          <value manuallyCreated="true" value="'negative'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList guid="7eb613d1-021a-11dd-76ee-0016e677cf72" enumerationDisplayCount="50" eDataType="#//indebtedness_report">
        <dataTypeName manuallyCreated="true" value="indebtedness_report"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration manuallyCreated="true" value="true"/>
        <enumerationElements guid="7ea7bbf1-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="none"/>
          <value manuallyCreated="true" value="'none'"/>
        </enumerationElements>
        <enumerationElements guid="7ea57201-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="some"/>
          <value manuallyCreated="true" value="'some'"/>
        </enumerationElements>
        <enumerationElements guid="7e7f4c61-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="many"/>
          <value manuallyCreated="true" value="'many'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList guid="7ea0b710-021a-11dd-76ee-0016e677cf72" enumerationDisplayCount="50" eDataType="#//neighbourhood">
        <dataTypeName manuallyCreated="true" value="neighbourhood"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration manuallyCreated="true" value="true"/>
        <enumerationElements guid="7eaee7e0-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="luxurious"/>
          <value manuallyCreated="true" value="'luxurious'"/>
        </enumerationElements>
        <enumerationElements guid="7e736582-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="normal"/>
          <value manuallyCreated="true" value="'normal'"/>
        </enumerationElements>
        <enumerationElements guid="7e925f32-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="poor"/>
          <value manuallyCreated="true" value="'poor'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList guid="7e8da443-021a-11dd-76ee-0016e677cf72" enumerationDisplayCount="50" eDataType="#//offer_new">
        <dataTypeName manuallyCreated="true" value="offer_new"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration manuallyCreated="true" value="true"/>
        <enumerationElements guid="7ec46bb3-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="announce_lower_offer"/>
          <value manuallyCreated="true" value="'announce_lower_offer'"/>
        </enumerationElements>
        <enumerationElements guid="7e81bd61-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="announce_existing_offer"/>
          <value manuallyCreated="true" value="'announce_existing_offer'"/>
        </enumerationElements>
        <enumerationElements guid="7ea0b713-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="higher_offer_possible"/>
          <value manuallyCreated="true" value="'higher_offer_possible'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList guid="7e81bd60-021a-11dd-76ee-0016e677cf72" enumerationDisplayCount="50" eDataType="#//customer_type">
        <dataTypeName manuallyCreated="true" value="customer_type"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration manuallyCreated="true" value="true"/>
        <enumerationElements guid="7e8b3342-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="Private_customer"/>
          <value manuallyCreated="true" value="'Private customer'"/>
        </enumerationElements>
        <enumerationElements guid="7eaa2cf3-021a-11dd-76ee-0016e677cf72">
          <label manuallyCreated="true" value="Business_customer"/>
          <value manuallyCreated="true" value="'Business customer'"/>
        </enumerationElements>
      </customDataTypeList>
    </contents>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EEnum" name="type">
    <eLiterals name="Small_car" literal="'Small_car'"/>
    <eLiterals name="Convertible" value="1" literal="'Convertible'"/>
    <eLiterals name="Van" value="2" literal="'Van'"/>
    <eLiterals name="Combi" value="3" literal="'Combi'"/>
    <eLiterals name="Middle_class_car" value="4" literal="'Middle_class_car'"/>
    <eLiterals name="Limousine" value="5" literal="'Limousine'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="company_size">
    <eLiterals name="big" literal="'big'"/>
    <eLiterals name="medium" value="1" literal="'medium'"/>
    <eLiterals name="small" value="2" literal="'small'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="business_register">
    <eLiterals name="negative" literal="'negative'"/>
    <eLiterals name="positive" value="1" literal="'positive'"/>
    <eLiterals name="very_negative" value="2" literal="'very_negative'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="title">
    <eLiterals name="Mr_" literal="'Mr.'"/>
    <eLiterals name="Mrs_" value="1" literal="'Mrs.'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="credit_provision">
    <eLiterals name="approved" literal="'approved'"/>
    <eLiterals name="rejected" value="1" literal="'rejected'"/>
    <eLiterals name="scrutinize" value="2" literal="'scrutinize'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="job_category">
    <eLiterals name="Public_servant" literal="'Public_servant'"/>
    <eLiterals name="Independant" value="1" literal="'Independant'"/>
    <eLiterals name="Freelancer" value="2" literal="'Freelancer'"/>
    <eLiterals name="Unemployes" value="3" literal="'Unemployes'"/>
    <eLiterals name="Houswife_man" value="4" literal="'Houswife_man'"/>
    <eLiterals name="Pupil" value="5" literal="'Pupil'"/>
    <eLiterals name="Trainee" value="6" literal="'Trainee'"/>
    <eLiterals name="Student" value="7" literal="'Student'"/>
    <eLiterals name="Worker" value="8" literal="'Worker'"/>
    <eLiterals name="Employee" value="9" literal="'Employee'"/>
    <eLiterals name="Pensioner" value="10" literal="'Pensioner'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="marital_status">
    <eLiterals name="married" literal="'married'"/>
    <eLiterals name="single" value="1" literal="'single'"/>
    <eLiterals name="spouse" value="2" literal="'spouse'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="customer_rating">
    <eLiterals name="positive" literal="'positive'"/>
    <eLiterals name="neutral" value="1" literal="'neutral'"/>
    <eLiterals name="negative" value="2" literal="'negative'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="indebtedness_report">
    <eLiterals name="none" literal="'none'"/>
    <eLiterals name="some" value="1" literal="'some'"/>
    <eLiterals name="many" value="2" literal="'many'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="neighbourhood">
    <eLiterals name="luxurious" literal="'luxurious'"/>
    <eLiterals name="normal" value="1" literal="'normal'"/>
    <eLiterals name="poor" value="2" literal="'poor'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="offer_new">
    <eLiterals name="announce_lower_offer" literal="'announce_lower_offer'"/>
    <eLiterals name="announce_existing_offer" value="1" literal="'announce_existing_offer'"/>
    <eLiterals name="higher_offer_possible" value="2" literal="'higher_offer_possible'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="customer_type">
    <eLiterals name="Private_customer" literal="'Private customer'"/>
    <eLiterals name="Business_customer" value="1" literal="'Business customer'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="company_address">
    <eLiterals name="Germany" literal="'Germany'"/>
    <eLiterals name="EU" value="1" literal="'EU'"/>
    <eLiterals name="others" value="2" literal="'other'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="form_of_business">
    <eLiterals name="public_company" literal="'public_company'"/>
    <eLiterals name="Sole_proprietorship" value="1" literal="'Sole proprietorship'"/>
    <eLiterals name="others" value="2" literal="'other'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension" guid="7e925f30-021a-11dd-76ee-0016e677cf72">
        <name manuallyCreated="true" value="Vehicle"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicle_offer" lowerBound="1" upperBound="-1" eType="#//Vehicle_offer" eOpposite="#//Vehicle_offer/vehicle">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension" guid="7ed2c390-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="vehicle_offer"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year_of_manufacture_" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e8da440-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="year_of_manufacture_"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vehicle_ID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e5b97c0-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="vehicle_ID"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="model" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e69efa2-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="model"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e867853-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="price"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//type">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7eac9df1-021a-11dd-76ee-0016e677cf72" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.0">
          <name manuallyCreated="true" value="type"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension" guid="cf6df850-694a-11dd-392a-001d09547911">
        <name manuallyCreated="true" value="Customer"/>
      </contents>
    </eAnnotations>
    <eAnnotations source="Vocabulary"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" lowerBound="1" eType="#//title">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7ebfb0c0-021a-11dd-76ee-0016e677cf72" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.5">
          <name manuallyCreated="true" value="title"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cdNR" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e736581-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="cdNR"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credit_provision" lowerBound="1" eType="#//credit_provision">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e6c3990-021a-11dd-76ee-0016e677cf72" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.6">
          <name manuallyCreated="true" value="credit_provision"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_credit_amount" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e6c3992-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="max_credit_amount"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="positive_money_availability" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e971a23-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="positive_money_availability"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="worthiness" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7ec46bb2-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="worthiness"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="desired_credit_amount" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="af7b6f15-5954-11dd-1645-001f3bc18777">
          <name manuallyCreated="true" value="desired_credit_amount"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="granted_credit_amount" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="6009f492-596f-11dd-783b-001d09547911">
          <name manuallyCreated="true" value="granted_credit_amount"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contact_person" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7ec46bb1-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="contact_person"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicle_offer" lowerBound="1" eType="#//Vehicle_offer" eOpposite="#//Vehicle_offer/customer">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension" guid="7e884e56-742f-11dd-392a-001d09547911">
          <name manuallyCreated="true" value="vehicle_offer"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle_offer">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension" guid="7eb613d0-021a-11dd-76ee-0016e677cf72">
        <name manuallyCreated="true" value="Vehicle_offer"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customer" lowerBound="1" upperBound="-1" eType="#//Customer" eOpposite="#//Customer/vehicle_offer">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension" guid="7e884e55-742f-11dd-392a-001d09547911">
          <name manuallyCreated="true" value="customer"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicle" lowerBound="1" eType="#//Vehicle" eOpposite="#//Vehicle/vehicle_offer">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension" guid="7ed50d81-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="vehicle"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offer_new" lowerBound="1" eType="#//offer_new">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e867852-021a-11dd-76ee-0016e677cf72" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.12">
          <name manuallyCreated="true" value="offer_new"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offer_new_percent" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e9e4613-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="offer_new_percent"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offer_ok" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e56dcd1-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="offer_ok"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offer_ID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e7f4c60-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="offer_ID"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offer_date" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e8da441-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="offer_date"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="Subtype" value="FullDateTime"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="total_amount" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e998b20-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="total_amount"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="customers_max" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e971a20-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="customers_max"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="customer_offer" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e7f4c63-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="customer_offer"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="customer_type" lowerBound="1" eType="#//customer_type">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7ec1fab4-021a-11dd-76ee-0016e677cf72" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.13">
          <name manuallyCreated="true" value="customer_type"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="proportional_surcharge" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7ebfb0c2-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="proportional_surcharge"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="customer_wish" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="e2cebf70-5d50-11dd-2025-001d09547911">
          <name manuallyCreated="true" value="customer_wish"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Business_customer" eSuperTypes="#//Customer">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension" guid="7ea30102-021a-11dd-76ee-0016e677cf72">
        <name manuallyCreated="true" value="Business_customer"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="car_purchases" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e736580-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="car_purchases"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount_unsettled_bills" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7ea57202-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="amount_unsettled_bills"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="years_since_first_purchase" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e56dcd0-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="years_since_first_purchase"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="company_size" lowerBound="1" eType="#//company_size">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7ebacec1-021a-11dd-76ee-0016e677cf72" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.1">
          <name manuallyCreated="true" value="company_size"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="company_name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e840751-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="company_name"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="company_address" eType="#//company_address">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7ea0b712-021a-11dd-76ee-0016e677cf72" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.2">
          <name manuallyCreated="true" value="company_address"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="business_register" lowerBound="1" eType="#//business_register">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7ea7bbf0-021a-11dd-76ee-0016e677cf72" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.3">
          <name manuallyCreated="true" value="business_register"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annual_turnover" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7ea57200-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="annual_turnover"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="form_of_business" lowerBound="1" eType="#//form_of_business">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e88e950-021a-11dd-76ee-0016e677cf72" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.4">
          <name manuallyCreated="true" value="form_of_business"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Private_customer" eSuperTypes="#//Customer">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension" guid="7e8b3340-021a-11dd-76ee-0016e677cf72">
        <name manuallyCreated="true" value="Private_customer"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expenses" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e5926c1-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="expenses"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="job_category" lowerBound="1" eType="#//job_category">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e998b22-021a-11dd-76ee-0016e677cf72" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.7">
          <name manuallyCreated="true" value="job_category"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="income" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e925f31-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="income"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adults_in_household" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7eb3c9e1-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="adults_in_household"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="marital_status" lowerBound="1" eType="#//marital_status">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7ea30100-021a-11dd-76ee-0016e677cf72" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.8">
          <name manuallyCreated="true" value="marital_status"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="age" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7ec1fab1-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="age"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="money_availability" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e546bd0-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="money_availability"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="money_deposit" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7ec6b5a1-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="money_deposit"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="children" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7ec926a2-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="children"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credit_worthiness" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e7cdb62-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="credit_worthiness"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="customer_rating" lowerBound="1" eType="#//customer_rating">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e9e4612-021a-11dd-76ee-0016e677cf72" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.9">
          <name manuallyCreated="true" value="customer_rating"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cost_of_living" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e6c3991-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="cost_of_living"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="monthly_foreign_credit_rates" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e70f480-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="monthly_foreign_credit_rates"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indebtedness_report" lowerBound="1" eType="#//indebtedness_report">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7e9bd511-021a-11dd-76ee-0016e677cf72" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.10">
          <name manuallyCreated="true" value="indebtedness_report"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nationality" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7ebacec0-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="nationality"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="neighbourhood" lowerBound="1" eType="#//neighbourhood">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7eb3c9e2-021a-11dd-76ee-0016e677cf72" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.11">
          <name manuallyCreated="true" value="neighbourhood"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="solvency" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" guid="7ec46bb0-021a-11dd-76ee-0016e677cf72">
          <name manuallyCreated="true" value="solvency"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
      <eAnnotations source="Vocabulary">
        <details key="SourceObjectTypeName" value="OT_CLS"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
