<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:com.corticon.rulesemf.canonicalvocabularymodel="http:///com/corticon/rulesemf/canonicalvocabularymodel.ecore" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="root" nsURI="http://root/1.0" nsPrefix="root">
  <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
    <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:RootExtension" majorVersionNumber="1" minorVersionNumber="3" buildNumber="8020" updateStamp="_MCS3caeOEeyCxPBNdjP98A" externalChecksum="547642878:507989954" studioType="Javascript" customDataTypeDisplayCount="37">
      <languageCode>en_US</languageCode>
      <databaseAccess databasePropertyDisplayCount="50"/>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//UIControlType">
        <dataTypeName manuallyCreated="true" value="UIControlType"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Text'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'SingleChoice'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'MultipleChoices'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'DateTime'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Number'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'ReadOnlyText'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'YesNo'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'TextArea'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'FileUpload'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'MultiExpenses'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="51" eDataType="#//StageList">
        <dataTypeName manuallyCreated="true" value="StageList"/>
        <baseDataType manuallyCreated="true" value="Integer"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="0"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="2"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="3"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="4"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="5"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="6"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="7"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="8"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="9"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="10"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="11"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="12"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="13"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="14"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="15"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="16"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="17"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="18"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="19"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="20"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="21"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="999"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//YesNoAnswer">
        <dataTypeName manuallyCreated="true" value="YesNoAnswer"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'yes'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'no'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//LabelPosition">
        <dataTypeName manuallyCreated="true" value="LabelPosition"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Above'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Side'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//ClaimReason">
        <dataTypeName manuallyCreated="true" value="ClaimReason"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <label manuallyCreated="true" value="tripCancel"/>
          <value manuallyCreated="true" value="'tripCancel'"/>
        </enumerationElements>
        <enumerationElements>
          <label manuallyCreated="true" value="somethingHappened"/>
          <value manuallyCreated="true" value="'somethingHappened'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//ClaimReasonCancel">
        <dataTypeName manuallyCreated="true" value="ClaimReasonCancel"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <label manuallyCreated="true" value="Sick"/>
          <value manuallyCreated="true" value="'Sick'"/>
        </enumerationElements>
        <enumerationElements>
          <label manuallyCreated="true" value="Injury"/>
          <value manuallyCreated="true" value="'Injury'"/>
        </enumerationElements>
        <enumerationElements>
          <label manuallyCreated="true" value="UnexpDeath"/>
          <value manuallyCreated="true" value="'UnexpDeath'"/>
        </enumerationElements>
        <enumerationElements>
          <label manuallyCreated="true" value="Weather"/>
          <value manuallyCreated="true" value="'Weather'"/>
        </enumerationElements>
        <enumerationElements>
          <label manuallyCreated="true" value="JobRel"/>
          <value manuallyCreated="true" value="'JobRel'"/>
        </enumerationElements>
        <enumerationElements>
          <label manuallyCreated="true" value="OtherReason"/>
          <value manuallyCreated="true" value="'OtherReason'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//DuringTripIssue">
        <dataTypeName manuallyCreated="true" value="DuringTripIssue"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <label manuallyCreated="true" value="TravelDelay"/>
          <value manuallyCreated="true" value="'TravelDelay'"/>
        </enumerationElements>
        <enumerationElements>
          <label manuallyCreated="true" value="BelongingsBaggage"/>
          <value manuallyCreated="true" value="'BelongingsBaggage'"/>
        </enumerationElements>
        <enumerationElements>
          <label manuallyCreated="true" value="SickOrInjuryInTrip"/>
          <value manuallyCreated="true" value="'SickOrInjuryInTrip'"/>
        </enumerationElements>
        <enumerationElements>
          <label manuallyCreated="true" value="OtherEvent"/>
          <value manuallyCreated="true" value="'OtherEvent'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//WhoIsSick">
        <dataTypeName manuallyCreated="true" value="WhoIsSick"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <label manuallyCreated="true" value="Me"/>
          <value manuallyCreated="true" value="'Me'"/>
        </enumerationElements>
        <enumerationElements>
          <label manuallyCreated="true" value="SomeoneElse"/>
          <value manuallyCreated="true" value="'SomeoneElse'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//ClaimPolicyType">
        <dataTypeName manuallyCreated="true" value="ClaimPolicyType"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <label manuallyCreated="true" value="Individual"/>
          <value manuallyCreated="true" value="'Individual'"/>
        </enumerationElements>
        <enumerationElements>
          <label manuallyCreated="true" value="Multiple"/>
          <value manuallyCreated="true" value="'Multiple'"/>
        </enumerationElements>
      </customDataTypeList>
      <vocabularyMappings name="JSON" ID="JSON" mappingType="JSON"/>
    </contents>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="UIControl">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="UIControl"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="label"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="value"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="required"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//UIControlType">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.0">
          <name manuallyCreated="true" value="type"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="defaultValue"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="id"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="fieldName"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="min"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="max"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxDT" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="maxDT"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minDT" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="minDT"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="option" upperBound="-1" eType="#//Option">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="option"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tooltip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="tooltip"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validationErrorMsg" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="validationErrorMsg"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelPosition" eType="#//LabelPosition">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.3">
          <name manuallyCreated="true" value="labelPosition"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cols" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="cols"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rows" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="rows"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="dataSource"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Container"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="title"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uiControls" upperBound="-1" eType="#//UIControl">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="uiControls"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="id"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="description"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validationMsg" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="validationMsg"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UI">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="UI"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containers" lowerBound="1" upperBound="-1" eType="#//Container">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="containers"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentStageNumber" eType="#//StageList">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.1">
          <name manuallyCreated="true" value="currentStageNumber"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nextStageNumber" eType="#//StageList">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.1">
          <name manuallyCreated="true" value="nextStageNumber"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="done" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="done"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comments" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="comments"/>
          <mode manuallyCreated="true" value="ExtendedTransient"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dt1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="dt1"/>
          <mode manuallyCreated="true" value="ExtendedTransient"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="str1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="str1"/>
          <mode manuallyCreated="true" value="ExtendedTransient"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="str2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="str2"/>
          <mode manuallyCreated="true" value="ExtendedTransient"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathToData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="pathToData"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noUiToRenderContinue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="noUiToRenderContinue"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelPosition" eType="#//LabelPosition">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.3">
          <name manuallyCreated="true" value="labelPosition"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stageOnExit" eType="#//StageList">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.1">
          <name manuallyCreated="true" value="stageOnExit"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="language"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UIControlType">
    <eLiterals name="V0" literal="'Text'"/>
    <eLiterals name="V1" value="1" literal="'SingleChoice'"/>
    <eLiterals name="V2" value="2" literal="'MultipleChoices'"/>
    <eLiterals name="V3" value="3" literal="'DateTime'"/>
    <eLiterals name="V4" value="4" literal="'Number'"/>
    <eLiterals name="V5" value="5" literal="'ReadOnlyText'"/>
    <eLiterals name="V6" value="6" literal="'YesNo'"/>
    <eLiterals name="V7" value="7" literal="'TextArea'"/>
    <eLiterals name="V8" value="8" literal="'FileUpload'"/>
    <eLiterals name="V9" value="9" literal="'MultiExpenses'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Option">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Option"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="value"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="displayName"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="YesNoAnswer">
    <eLiterals name="V0" literal="'yes'"/>
    <eLiterals name="V1" value="1" literal="'no'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LabelPosition">
    <eLiterals name="V0" literal="'Above'"/>
    <eLiterals name="V1" value="1" literal="'Side'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ClaimReason">
    <eLiterals name="tripCancel" literal="'tripCancel'"/>
    <eLiterals name="somethingHappened" value="1" literal="'somethingHappened'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ClaimReasonCancel">
    <eLiterals name="Sick" literal="'Sick'"/>
    <eLiterals name="Injury" value="1" literal="'Injury'"/>
    <eLiterals name="UnexpDeath" value="2" literal="'UnexpDeath'"/>
    <eLiterals name="Weather" value="3" literal="'Weather'"/>
    <eLiterals name="JobRel" value="4" literal="'JobRel'"/>
    <eLiterals name="OtherReason" value="5" literal="'OtherReason'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ClaimPolicyType">
    <eLiterals name="Individual" literal="'Individual'"/>
    <eLiterals name="Multiple" value="1" literal="'Multiple'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DuringTripIssue">
    <eLiterals name="TravelDelay" literal="'TravelDelay'"/>
    <eLiterals name="BelongingsBaggage" value="1" literal="'BelongingsBaggage'"/>
    <eLiterals name="SickOrInjuryInTrip" value="2" literal="'SickOrInjuryInTrip'"/>
    <eLiterals name="OtherEvent" value="3" literal="'OtherEvent'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WhoIsSick">
    <eLiterals name="Me" literal="'Me'"/>
    <eLiterals name="SomeoneElse" value="1" literal="'SomeoneElse'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StageList">
    <eLiterals name="V0" literal="0"/>
    <eLiterals name="V1" value="1" literal="1"/>
    <eLiterals name="V2" value="2" literal="2"/>
    <eLiterals name="V3" value="3" literal="3"/>
    <eLiterals name="V4" value="4" literal="4"/>
    <eLiterals name="V5" value="5" literal="5"/>
    <eLiterals name="V6" value="6" literal="6"/>
    <eLiterals name="V7" value="7" literal="7"/>
    <eLiterals name="V8" value="8" literal="8"/>
    <eLiterals name="V9" value="9" literal="9"/>
    <eLiterals name="V10" value="10" literal="10"/>
    <eLiterals name="V11" value="11" literal="11"/>
    <eLiterals name="V12" value="12" literal="12"/>
    <eLiterals name="V13" value="13" literal="13"/>
    <eLiterals name="V14" value="14" literal="14"/>
    <eLiterals name="V15" value="15" literal="15"/>
    <eLiterals name="V16" value="16" literal="16"/>
    <eLiterals name="V17" value="17" literal="17"/>
    <eLiterals name="V18" value="18" literal="18"/>
    <eLiterals name="V19" value="19" literal="19"/>
    <eLiterals name="V20" value="20" literal="20"/>
    <eLiterals name="V21" value="21" literal="21"/>
    <eLiterals name="V22" value="22" literal="999"/>
  </eClassifiers>
  <eSubpackages name="ProjectsData" nsURI="http://root/ProjectsData/1.0" nsPrefix="root.ProjectsData">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:DomainExtension">
        <name manuallyCreated="true" value="ProjectsData"/>
      </contents>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="CanonicalSample">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
          <name manuallyCreated="true" value="CanonicalSample"/>
          <datastorePersistent manuallyCreated="true" value="false"/>
          <datastoreCaching manuallyCreated="true" value="false"/>
        </contents>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Step1Field1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="Step1Field1"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Step1Field2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="Step1Field2"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Step1Field3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="Step1Field3"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Step2Field1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="Step2Field1"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Step3Field1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="Step3Field1"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Step4Field1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="Step4Field1"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Step4Field2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="Step4Field2"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Step5Field1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="Step5Field1"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Step6Field1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="Step6Field1"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Step7Field1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="Step7Field1"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Step8Field1" upperBound="-1" eType="#//ProjectsData/Expense">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
            <name manuallyCreated="true" value="Step8Field1"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Step8USDSum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="Step8USDSum"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Step8EurSum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="Step8EurSum"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Step8HotelUSDSum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="Step8HotelUSDSum"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Step8SumAll" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="Step8SumAll"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IncomeTaxSample">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
          <name manuallyCreated="true" value="IncomeTaxSample"/>
          <datastorePersistent manuallyCreated="true" value="false"/>
          <datastoreCaching manuallyCreated="true" value="false"/>
        </contents>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hadInvestmentIncome" eType="#//YesNoAnswer">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.2">
            <name manuallyCreated="true" value="hadInvestmentIncome"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="salaryIncome" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="salaryIncome"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="longStockGains" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="longStockGains"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortStockGains" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="shortStockGains"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalIncome" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="totalIncome"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalTaxes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="totalTaxes"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="taxRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="taxRate"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dividends" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="dividends"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Data">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
          <name manuallyCreated="true" value="Data"/>
          <datastorePersistent manuallyCreated="true" value="false"/>
          <datastoreCaching manuallyCreated="true" value="false"/>
        </contents>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="canonicalSample" eType="#//ProjectsData/CanonicalSample">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
            <name manuallyCreated="true" value="canonicalSample"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incomeTaxSample" eType="#//ProjectsData/IncomeTaxSample">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
            <name manuallyCreated="true" value="incomeTaxSample"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="validationSample" eType="#//ProjectsData/ValidationSample">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
            <name manuallyCreated="true" value="validationSample"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="claim" eType="#//ProjectsData/Claim">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
            <name manuallyCreated="true" value="claim"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="reusingSubflows" eType="#//ProjectsData/ReusingSubflows">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
            <name manuallyCreated="true" value="reusingSubflows"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="jobApplication" eType="#//ProjectsData/JobApplication">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
            <name manuallyCreated="true" value="jobApplication"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ValidationSample">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
          <name manuallyCreated="true" value="ValidationSample"/>
          <datastorePersistent manuallyCreated="true" value="false"/>
          <datastoreCaching manuallyCreated="true" value="false"/>
        </contents>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="number1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="number1"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="number2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="number2"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sumStep1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="sumStep1"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Claim">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
          <name manuallyCreated="true" value="Claim"/>
          <datastorePersistent manuallyCreated="true" value="false"/>
          <datastoreCaching manuallyCreated="true" value="false"/>
        </contents>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="reason" eType="#//ClaimReason">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.4">
            <name manuallyCreated="true" value="reason"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="reasonCancel" eType="#//ClaimReasonCancel">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.5">
            <name manuallyCreated="true" value="reasonCancel"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="duringTripIssue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="duringTripIssue"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="policyType" eType="#//ClaimPolicyType">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.8">
            <name manuallyCreated="true" value="policyType"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="whoSick" eType="#//WhoIsSick">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.7">
            <name manuallyCreated="true" value="whoSick"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasDoctorAdvised" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="hasDoctorAdvised"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="whenCancel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="whenCancel"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="haveContactedUs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="haveContactedUs"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReusingSubflows">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
          <name manuallyCreated="true" value="ReusingSubflows"/>
          <datastorePersistent manuallyCreated="true" value="false"/>
          <datastoreCaching manuallyCreated="true" value="false"/>
        </contents>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Step1Field1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="Step1Field1"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SubflowField1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="SubflowField1"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SubflowField2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="SubflowField2"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Step2Field1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="Step2Field1"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Step3Field1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="Step3Field1"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Expense">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
          <name manuallyCreated="true" value="Expense"/>
          <datastorePersistent manuallyCreated="true" value="false"/>
          <datastoreCaching manuallyCreated="true" value="false"/>
        </contents>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="currency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="currency"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="amount"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expenseCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="expenseCode"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JobApplication">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
          <name manuallyCreated="true" value="JobApplication"/>
          <datastorePersistent manuallyCreated="true" value="false"/>
          <datastoreCaching manuallyCreated="true" value="false"/>
        </contents>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="italianCitizen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
          <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
            <name manuallyCreated="true" value="italianCitizen"/>
            <mode manuallyCreated="true" value="Base"/>
          </contents>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
