<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:com.corticon.rulesemf.canonicalvocabularymodel="http:///com/corticon/rulesemf/canonicalvocabularymodel.ecore" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="root" nsURI="http://root/1.0" nsPrefix="root">
  <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
    <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:RootExtension" majorVersionNumber="2" minorVersionNumber="2" buildNumber="8022" updateStamp="_CaK-MOQDEe-6C-_YfrLOLQ" externalChecksum="2722078124:507989954" studioType="Javascript" customDataTypeDisplayCount="50">
      <languageCode>en_US</languageCode>
      <databaseAccess databasePropertyDisplayCount="50"/>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//transport_type">
        <dataTypeName manuallyCreated="true" value="transport_type"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Rail'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Agriculture Equipment'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Forestry Equipment'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Industry Equipment'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Household Equipment'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Ship and Boat'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Locomotives'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Aircraft'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Agricultural Equipment'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Construction Equipment'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Lawn and Garden Equipment'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Airport Equipment'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Industrial/Commercial Equipment'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Logging Equipment'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Railroad Equipment'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Recreational Equipment'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//vehicle_or_engine_type">
        <dataTypeName manuallyCreated="true" value="vehicle_or_engine_type"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'4 Stroke'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'2 Stroke'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Off Road Trucks'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//vehicle_type">
        <dataTypeName manuallyCreated="true" value="vehicle_type"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Passenger Cars'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Motorcycles'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Diesel Buses (Diesel Heavy-Duty Vehicles)'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Other 2-axle, 4-Tire Vehicles'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Single unit 2-Axle 6-Tire or More Trucks'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Combination Trucks'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//vehicle_class">
        <dataTypeName manuallyCreated="true" value="vehicle_class"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Passenger Cars'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Light Duty Cars'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Light Duty Trucks'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Medium Duty Trucks'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Medium Duty Vehicles'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Heavy Duty Vehicles'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Heavy Duty Trucks'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Bus'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Motorcycles'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Light Duty Vehicles'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Vans'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Motorbike'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'HGV - Rigid'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'HGV - Articulated'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'HGV - Type Unknown'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="47" eDataType="#//transit_class">
        <dataTypeName manuallyCreated="true" value="transit_class"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Average Passenger'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Economy Class'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Business Class'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Premium Economy Class'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'First Class'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Light Rail and Tram'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'National Rail'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Local Bus'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Coach'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Average Local Bus'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'&lt; 300 miles'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'>= 300 miles and &lt; 2300 miles'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'>= 2300 miles'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Northeast Corridor'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Other Routes'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'National Average'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Subway, Tram'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="49" eDataType="#//transit_type">
        <dataTypeName manuallyCreated="true" value="transit_type"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Air - Domestic'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Air - Short Haul, up to 3700km distance'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Air - Long Haul, over 3700km distance'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Air - International'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Rail'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Taxi'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Bus'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Average Ferry'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Air Travel - Short Haul'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Air - Medium Haul'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Air - Long Haul'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Intercity Rail'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Commuter Rail'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Transit Rail'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//travel_mode">
        <dataTypeName manuallyCreated="true" value="travel_mode"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'air'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'car'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'rail'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//car_type">
        <dataTypeName manuallyCreated="true" value="car_type"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'petrol'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'diesel'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'hybrid'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'plugin_hybrid'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'battery'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'average'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//car_size">
        <dataTypeName manuallyCreated="true" value="car_size"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'small'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'medium'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'large'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//air_class">
        <dataTypeName manuallyCreated="true" value="air_class"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'economy'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'first'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'business'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'average'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//haul_distance_classification">
        <dataTypeName manuallyCreated="true" value="haul_distance_classification"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Short'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Medium'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Long'"/>
        </enumerationElements>
      </customDataTypeList>
      <vocabularyMappings name="JSON" ID="JSON" mappingType="JSON"/>
    </contents>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Combustion">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Combustion"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="category"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="type"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="factor" upperBound="-1" eType="#//Factor" eOpposite="#//Factor/combustion">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="factor"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="region" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="region"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transport_type" eType="#//transport_type">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.0">
          <name manuallyCreated="true" value="transport_type"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vehicle_or_engine_type" eType="#//vehicle_or_engine_type">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.1">
          <name manuallyCreated="true" value="vehicle_or_engine_type"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicle" lowerBound="1" eType="#//Vehicle" eOpposite="#//Vehicle/combustion">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="vehicle"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Factor">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Factor"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="energy_basis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="energy_basis"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mass_basis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="mass_basis"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="heating_value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="heating_value"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="combustion" lowerBound="1" eType="#//Combustion" eOpposite="#//Combustion/factor">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="combustion"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fuel_density_liquid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="fuel_density_liquid"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fuel_density_gas" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="fuel_density_gas"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="liquid_basis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="liquid_basis"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gas_basis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="gas_basis"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="unit"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower_heating_value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="lower_heating_value"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stationary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="stationary"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="chemical" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="chemical"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fossil" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="fossil"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biogenic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="biogenic"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit_numerator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="unit_numerator"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="measure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="measure"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="value"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="transport_type">
    <eLiterals name="V0" literal="'Rail'"/>
    <eLiterals name="V1" value="1" literal="'Agriculture Equipment'"/>
    <eLiterals name="V2" value="2" literal="'Forestry Equipment'"/>
    <eLiterals name="V3" value="3" literal="'Industry Equipment'"/>
    <eLiterals name="V4" value="4" literal="'Household Equipment'"/>
    <eLiterals name="V5" value="5" literal="'Ship and Boat'"/>
    <eLiterals name="V6" value="6" literal="'Locomotives'"/>
    <eLiterals name="V7" value="7" literal="'Aircraft'"/>
    <eLiterals name="V8" value="8" literal="'Agricultural Equipment'"/>
    <eLiterals name="V9" value="9" literal="'Construction Equipment'"/>
    <eLiterals name="V10" value="10" literal="'Lawn and Garden Equipment'"/>
    <eLiterals name="V11" value="11" literal="'Airport Equipment'"/>
    <eLiterals name="V12" value="12" literal="'Industrial/Commercial Equipment'"/>
    <eLiterals name="V13" value="13" literal="'Logging Equipment'"/>
    <eLiterals name="V14" value="14" literal="'Railroad Equipment'"/>
    <eLiterals name="V15" value="15" literal="'Recreational Equipment'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="vehicle_or_engine_type">
    <eLiterals name="V0" literal="'4 Stroke'"/>
    <eLiterals name="V1" value="1" literal="'2 Stroke'"/>
    <eLiterals name="V2" value="2" literal="'Off Road Trucks'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="vehicle_type">
    <eLiterals name="V0" literal="'Passenger Cars'"/>
    <eLiterals name="V1" value="1" literal="'Motorcycles'"/>
    <eLiterals name="V2" value="2" literal="'Diesel Buses (Diesel Heavy-Duty Vehicles)'"/>
    <eLiterals name="V3" value="3" literal="'Other 2-axle, 4-Tire Vehicles'"/>
    <eLiterals name="V4" value="4" literal="'Single unit 2-Axle 6-Tire or More Trucks'"/>
    <eLiterals name="V5" value="5" literal="'Combination Trucks'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Vehicle"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vehicle_type" eType="#//vehicle_type">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.2">
          <name manuallyCreated="true" value="vehicle_type"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mpg" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="mpg"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kmL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="kmL"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="year"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="combustion" eType="#//Combustion" eOpposite="#//Combustion/vehicle">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="combustion"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="region" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="region"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="class" eType="#//vehicle_class">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.3">
          <name manuallyCreated="true" value="class"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="size"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fuel_type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="fuel_type"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percent_weight_laden" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="percent_weight_laden"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="public_transit_class" eType="#//transit_class">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.4">
          <name manuallyCreated="true" value="public_transit_class"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="public_transit_type" eType="#//transit_type">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.5">
          <name manuallyCreated="true" value="public_transit_type"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trip" lowerBound="1" eType="#//Trip" eOpposite="#//Trip/vehicle">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="trip"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="vehicle_class">
    <eLiterals name="V0" literal="'Passenger Cars'"/>
    <eLiterals name="V1" value="1" literal="'Light Duty Cars'"/>
    <eLiterals name="V2" value="2" literal="'Light Duty Trucks'"/>
    <eLiterals name="V3" value="3" literal="'Medium Duty Trucks'"/>
    <eLiterals name="V4" value="4" literal="'Medium Duty Vehicles'"/>
    <eLiterals name="V5" value="5" literal="'Heavy Duty Vehicles'"/>
    <eLiterals name="V6" value="6" literal="'Heavy Duty Trucks'"/>
    <eLiterals name="V7" value="7" literal="'Bus'"/>
    <eLiterals name="V8" value="8" literal="'Motorcycles'"/>
    <eLiterals name="V9" value="9" literal="'Light Duty Vehicles'"/>
    <eLiterals name="V10" value="10" literal="'Vans'"/>
    <eLiterals name="V11" value="11" literal="'Motorbike'"/>
    <eLiterals name="V12" value="12" literal="'HGV - Rigid'"/>
    <eLiterals name="V13" value="13" literal="'HGV - Articulated'"/>
    <eLiterals name="V14" value="14" literal="'HGV - Type Unknown'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="transit_type">
    <eLiterals name="V0" literal="'Air - Domestic'"/>
    <eLiterals name="V1" value="1" literal="'Air - Short Haul, up to 3700km distance'"/>
    <eLiterals name="V2" value="2" literal="'Air - Long Haul, over 3700km distance'"/>
    <eLiterals name="V3" value="3" literal="'Air - International'"/>
    <eLiterals name="V4" value="4" literal="'Rail'"/>
    <eLiterals name="V5" value="5" literal="'Taxi'"/>
    <eLiterals name="V6" value="6" literal="'Bus'"/>
    <eLiterals name="V7" value="7" literal="'Average Ferry'"/>
    <eLiterals name="V8" value="8" literal="'Air Travel - Short Haul'"/>
    <eLiterals name="V9" value="9" literal="'Air - Medium Haul'"/>
    <eLiterals name="V10" value="10" literal="'Air - Long Haul'"/>
    <eLiterals name="V11" value="11" literal="'Intercity Rail'"/>
    <eLiterals name="V12" value="12" literal="'Commuter Rail'"/>
    <eLiterals name="V13" value="13" literal="'Transit Rail'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="transit_class">
    <eLiterals name="V0" literal="'Average Passenger'"/>
    <eLiterals name="V1" value="1" literal="'Economy Class'"/>
    <eLiterals name="V2" value="2" literal="'Business Class'"/>
    <eLiterals name="V3" value="3" literal="'Premium Economy Class'"/>
    <eLiterals name="V4" value="4" literal="'First Class'"/>
    <eLiterals name="V5" value="5" literal="'Light Rail and Tram'"/>
    <eLiterals name="V6" value="6" literal="'National Rail'"/>
    <eLiterals name="V7" value="7" literal="'Local Bus'"/>
    <eLiterals name="V8" value="8" literal="'Coach'"/>
    <eLiterals name="V9" value="9" literal="'Average Local Bus'"/>
    <eLiterals name="V10" value="10" literal="'&lt; 300 miles'"/>
    <eLiterals name="V11" value="11" literal="'>= 300 miles and &lt; 2300 miles'"/>
    <eLiterals name="V12" value="12" literal="'>= 2300 miles'"/>
    <eLiterals name="V13" value="13" literal="'Northeast Corridor'"/>
    <eLiterals name="V14" value="14" literal="'Other Routes'"/>
    <eLiterals name="V15" value="15" literal="'National Average'"/>
    <eLiterals name="V16" value="16" literal="'Subway, Tram'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trip">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Trip"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="travel_mode" eType="#//travel_mode">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.6">
          <name manuallyCreated="true" value="travel_mode"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance_km" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="distance_km"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="air_class" eType="#//air_class">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.9">
          <name manuallyCreated="true" value="air_class"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="car_type" eType="#//car_type">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.7">
          <name manuallyCreated="true" value="car_type"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="car_size" eType="#//car_size">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.8">
          <name manuallyCreated="true" value="car_size"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="haul_distance_classification" eType="#//haul_distance_classification">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.10">
          <name manuallyCreated="true" value="haul_distance_classification"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicle" upperBound="-1" eType="#//Vehicle" eOpposite="#//Vehicle/trip">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="vehicle"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="travel_mode">
    <eLiterals name="V0" literal="'air'"/>
    <eLiterals name="V1" value="1" literal="'car'"/>
    <eLiterals name="V2" value="2" literal="'rail'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="car_type">
    <eLiterals name="V0" literal="'petrol'"/>
    <eLiterals name="V1" value="1" literal="'diesel'"/>
    <eLiterals name="V2" value="2" literal="'hybrid'"/>
    <eLiterals name="V3" value="3" literal="'plugin_hybrid'"/>
    <eLiterals name="V4" value="4" literal="'battery'"/>
    <eLiterals name="V5" value="5" literal="'average'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="car_size">
    <eLiterals name="V0" literal="'small'"/>
    <eLiterals name="V1" value="1" literal="'medium'"/>
    <eLiterals name="V2" value="2" literal="'large'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="air_class">
    <eLiterals name="V0" literal="'economy'"/>
    <eLiterals name="V1" value="1" literal="'first'"/>
    <eLiterals name="V2" value="2" literal="'business'"/>
    <eLiterals name="V3" value="3" literal="'average'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="haul_distance_classification">
    <eLiterals name="V0" literal="'Short'"/>
    <eLiterals name="V1" value="1" literal="'Medium'"/>
    <eLiterals name="V2" value="2" literal="'Long'"/>
  </eClassifiers>
</ecore:EPackage>
