<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:com.corticon.rulesemf.canonicalvocabularymodel="http:///com/corticon/rulesemf/canonicalvocabularymodel.ecore" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="root" nsURI="http://root/1.0" nsPrefix="root">
  <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
    <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:RootExtension" majorVersionNumber="1" minorVersionNumber="4" buildNumber="8020" updateStamp="_OdplIEQGEe2a6ZLL2ouUJg" externalChecksum="2722078124:507989954" studioType="Javascript" customDataTypeDisplayCount="23">
      <languageCode>en_US</languageCode>
      <databaseAccess databasePropertyDisplayCount="50"/>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//UIControlType">
        <dataTypeName manuallyCreated="true" value="UIControlType"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Text'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'SingleChoice'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'MultipleChoices'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'DateTime'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Number'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'ReadOnlyText'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'YesNo'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'TextArea'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'FileUpload'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'MultiExpenses'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'MultipleChoicesMultiSelect'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="274" eDataType="#//StageList">
        <dataTypeName manuallyCreated="true" value="StageList"/>
        <baseDataType manuallyCreated="true" value="Integer"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="0"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="2"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="3"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="4"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="5"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="6"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="7"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="8"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="9"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="10"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="11"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="12"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="13"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="14"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="15"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="16"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="17"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="18"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="19"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="20"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="999"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="100"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="101"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="102"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="103"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="104"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="105"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="106"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="107"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="108"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="109"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="110"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="111"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="112"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="113"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="114"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="115"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="116"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="117"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="118"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="119"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="120"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="200"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="201"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="202"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="203"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="204"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="205"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="206"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="207"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="208"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="209"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="210"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="211"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="212"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="213"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="214"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="215"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="216"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="217"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="218"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="219"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="220"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="300"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="301"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="302"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="303"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="304"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="305"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="306"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="307"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="308"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="309"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="310"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="311"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="312"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="313"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="314"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="315"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="316"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="317"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="318"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="319"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="320"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="400"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="401"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="402"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="403"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="404"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="405"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="406"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="407"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="408"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="409"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="410"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="411"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="412"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="413"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="414"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="415"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="416"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="417"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="418"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="419"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="420"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="500"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="501"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="502"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="503"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="504"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="505"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="506"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="507"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="508"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="509"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="510"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="511"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="512"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="513"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="514"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="515"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="516"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="517"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="518"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="519"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="520"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="600"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="601"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="602"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="603"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="604"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="605"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="606"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="607"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="608"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="609"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="610"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="611"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="612"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="613"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="614"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="615"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="616"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="617"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="618"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="619"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="620"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="700"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="701"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="702"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="703"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="704"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="705"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="706"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="707"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="708"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="709"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="710"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="711"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="712"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="713"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="714"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="715"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="716"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="717"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="718"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="719"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="720"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="800"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="801"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="802"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="803"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="804"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="805"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="806"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="807"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="808"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="809"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="810"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="811"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="812"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="813"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="814"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="815"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="816"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="817"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="818"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="819"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="820"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="900"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="901"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="902"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="903"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="904"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="905"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="906"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="907"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="908"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="909"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="910"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="911"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="912"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="913"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="914"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="915"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="916"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="917"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="918"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="919"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="920"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1000"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1001"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1002"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1003"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1004"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1005"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1006"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1007"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1008"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1009"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1010"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1011"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1012"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1013"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1014"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1015"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1016"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1017"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1018"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1019"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1020"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1100"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1101"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1102"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1103"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1104"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1105"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1106"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1107"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1108"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1109"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1110"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1111"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1112"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1113"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1114"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1115"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1116"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1117"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1118"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1119"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1120"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1200"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1201"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1202"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1203"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1204"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1205"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1206"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1207"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1208"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1209"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1210"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1211"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1212"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1213"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1214"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1215"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1216"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1217"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1218"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1219"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="1220"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//YesNoAnswer">
        <dataTypeName manuallyCreated="true" value="YesNoAnswer"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'yes'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'no'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//LabelPosition">
        <dataTypeName manuallyCreated="true" value="LabelPosition"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Above'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Side'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="49" eDataType="#//SortOptions">
        <dataTypeName manuallyCreated="true" value="SortOptions"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'A to Z'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Z to A'"/>
        </enumerationElements>
      </customDataTypeList>
      <vocabularyMappings name="JSON" ID="JSON" mappingType="JSON"/>
    </contents>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="UIControl">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="UIControl"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="label"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="value"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="required"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//UIControlType">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.0">
          <name manuallyCreated="true" value="type"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="defaultValue"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="id"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="fieldName"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="min"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="max"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxDT" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="maxDT"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minDT" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="minDT"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="option" upperBound="-1" eType="#//Option">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="option"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tooltip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="tooltip"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validationErrorMsg" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="validationErrorMsg"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelPosition" eType="#//LabelPosition">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.3">
          <name manuallyCreated="true" value="labelPosition"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cols" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="cols"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rows" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="rows"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="dataSource"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataSourceOptions" eType="#//DataSourceOptions">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="dataSourceOptions"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiple" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="multiple"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="showTime"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sortOptions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="sortOptions"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Container"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="title"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uiControls" upperBound="-1" eType="#//UIControl">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="uiControls"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="id"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="description"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validationMsg" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="validationMsg"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UI">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="UI"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containers" lowerBound="1" upperBound="-1" eType="#//Container">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="containers"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentStageNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="currentStageNumber"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nextStageNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="nextStageNumber"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="done" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="done"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comments" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="comments"/>
          <mode manuallyCreated="true" value="ExtendedTransient"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dt1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="dt1"/>
          <mode manuallyCreated="true" value="ExtendedTransient"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="str1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="str1"/>
          <mode manuallyCreated="true" value="ExtendedTransient"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="str2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="str2"/>
          <mode manuallyCreated="true" value="ExtendedTransient"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathToData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="pathToData"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noUiToRenderContinue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="noUiToRenderContinue"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelPosition" eType="#//LabelPosition">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.3">
          <name manuallyCreated="true" value="labelPosition"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stageOnExit" eType="#//StageList">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.1">
          <name manuallyCreated="true" value="stageOnExit"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="language"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentStageDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="currentStageDescription"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UIControlType">
    <eLiterals name="V0" literal="'Text'"/>
    <eLiterals name="V1" value="1" literal="'SingleChoice'"/>
    <eLiterals name="V2" value="2" literal="'MultipleChoices'"/>
    <eLiterals name="V3" value="3" literal="'DateTime'"/>
    <eLiterals name="V4" value="4" literal="'Number'"/>
    <eLiterals name="V5" value="5" literal="'ReadOnlyText'"/>
    <eLiterals name="V6" value="6" literal="'YesNo'"/>
    <eLiterals name="V7" value="7" literal="'TextArea'"/>
    <eLiterals name="V8" value="8" literal="'FileUpload'"/>
    <eLiterals name="V9" value="9" literal="'MultiExpenses'"/>
    <eLiterals name="V10" value="10" literal="'MultipleChoicesMultiSelect'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Option">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Option"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="value"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="displayName"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="YesNoAnswer">
    <eLiterals name="V0" literal="'yes'"/>
    <eLiterals name="V1" value="1" literal="'no'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LabelPosition">
    <eLiterals name="V0" literal="'Above'"/>
    <eLiterals name="V1" value="1" literal="'Side'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StageList">
    <eLiterals name="V0" literal="0"/>
    <eLiterals name="V1" value="1" literal="1"/>
    <eLiterals name="V2" value="2" literal="2"/>
    <eLiterals name="V3" value="3" literal="3"/>
    <eLiterals name="V4" value="4" literal="4"/>
    <eLiterals name="V5" value="5" literal="5"/>
    <eLiterals name="V6" value="6" literal="6"/>
    <eLiterals name="V7" value="7" literal="7"/>
    <eLiterals name="V8" value="8" literal="8"/>
    <eLiterals name="V9" value="9" literal="9"/>
    <eLiterals name="V10" value="10" literal="10"/>
    <eLiterals name="V11" value="11" literal="11"/>
    <eLiterals name="V12" value="12" literal="12"/>
    <eLiterals name="V13" value="13" literal="13"/>
    <eLiterals name="V14" value="14" literal="14"/>
    <eLiterals name="V15" value="15" literal="15"/>
    <eLiterals name="V16" value="16" literal="16"/>
    <eLiterals name="V17" value="17" literal="17"/>
    <eLiterals name="V18" value="18" literal="18"/>
    <eLiterals name="V19" value="19" literal="19"/>
    <eLiterals name="V20" value="20" literal="20"/>
    <eLiterals name="V21" value="21" literal="21"/>
    <eLiterals name="V22" value="22" literal="999"/>
    <eLiterals name="V22" value="22" literal="100"/>
    <eLiterals name="V23" value="23" literal="101"/>
    <eLiterals name="V24" value="24" literal="102"/>
    <eLiterals name="V25" value="25" literal="103"/>
    <eLiterals name="V26" value="26" literal="104"/>
    <eLiterals name="V27" value="27" literal="105"/>
    <eLiterals name="V28" value="28" literal="106"/>
    <eLiterals name="V29" value="29" literal="107"/>
    <eLiterals name="V30" value="30" literal="108"/>
    <eLiterals name="V31" value="31" literal="109"/>
    <eLiterals name="V32" value="32" literal="110"/>
    <eLiterals name="V33" value="33" literal="111"/>
    <eLiterals name="V34" value="34" literal="112"/>
    <eLiterals name="V35" value="35" literal="113"/>
    <eLiterals name="V36" value="36" literal="114"/>
    <eLiterals name="V37" value="37" literal="115"/>
    <eLiterals name="V38" value="38" literal="116"/>
    <eLiterals name="V39" value="39" literal="117"/>
    <eLiterals name="V40" value="40" literal="118"/>
    <eLiterals name="V41" value="41" literal="119"/>
    <eLiterals name="V42" value="42" literal="120"/>
    <eLiterals name="V43" value="43" literal="200"/>
    <eLiterals name="V44" value="44" literal="201"/>
    <eLiterals name="V45" value="45" literal="202"/>
    <eLiterals name="V46" value="46" literal="203"/>
    <eLiterals name="V47" value="47" literal="204"/>
    <eLiterals name="V48" value="48" literal="205"/>
    <eLiterals name="V49" value="49" literal="206"/>
    <eLiterals name="V50" value="50" literal="207"/>
    <eLiterals name="V51" value="51" literal="208"/>
    <eLiterals name="V52" value="52" literal="209"/>
    <eLiterals name="V53" value="53" literal="210"/>
    <eLiterals name="V54" value="54" literal="211"/>
    <eLiterals name="V55" value="55" literal="212"/>
    <eLiterals name="V56" value="56" literal="213"/>
    <eLiterals name="V57" value="57" literal="214"/>
    <eLiterals name="V58" value="58" literal="215"/>
    <eLiterals name="V59" value="59" literal="216"/>
    <eLiterals name="V60" value="60" literal="217"/>
    <eLiterals name="V61" value="61" literal="218"/>
    <eLiterals name="V62" value="62" literal="219"/>
    <eLiterals name="V63" value="63" literal="220"/>
    <eLiterals name="V64" value="64" literal="300"/>
    <eLiterals name="V65" value="65" literal="301"/>
    <eLiterals name="V66" value="66" literal="302"/>
    <eLiterals name="V67" value="67" literal="303"/>
    <eLiterals name="V68" value="68" literal="304"/>
    <eLiterals name="V69" value="69" literal="305"/>
    <eLiterals name="V70" value="70" literal="306"/>
    <eLiterals name="V71" value="71" literal="307"/>
    <eLiterals name="V72" value="72" literal="308"/>
    <eLiterals name="V73" value="73" literal="309"/>
    <eLiterals name="V74" value="74" literal="310"/>
    <eLiterals name="V75" value="75" literal="311"/>
    <eLiterals name="V76" value="76" literal="312"/>
    <eLiterals name="V77" value="77" literal="313"/>
    <eLiterals name="V78" value="78" literal="314"/>
    <eLiterals name="V79" value="79" literal="315"/>
    <eLiterals name="V80" value="80" literal="316"/>
    <eLiterals name="V81" value="81" literal="317"/>
    <eLiterals name="V82" value="82" literal="318"/>
    <eLiterals name="V83" value="83" literal="319"/>
    <eLiterals name="V84" value="84" literal="320"/>
    <eLiterals name="V85" value="85" literal="400"/>
    <eLiterals name="V86" value="86" literal="401"/>
    <eLiterals name="V87" value="87" literal="402"/>
    <eLiterals name="V88" value="88" literal="403"/>
    <eLiterals name="V89" value="89" literal="404"/>
    <eLiterals name="V90" value="90" literal="405"/>
    <eLiterals name="V91" value="91" literal="406"/>
    <eLiterals name="V92" value="92" literal="407"/>
    <eLiterals name="V93" value="93" literal="408"/>
    <eLiterals name="V94" value="94" literal="409"/>
    <eLiterals name="V95" value="95" literal="410"/>
    <eLiterals name="V96" value="96" literal="411"/>
    <eLiterals name="V97" value="97" literal="412"/>
    <eLiterals name="V98" value="98" literal="413"/>
    <eLiterals name="V99" value="99" literal="414"/>
    <eLiterals name="V100" value="100" literal="415"/>
    <eLiterals name="V101" value="101" literal="416"/>
    <eLiterals name="V102" value="102" literal="417"/>
    <eLiterals name="V103" value="103" literal="418"/>
    <eLiterals name="V104" value="104" literal="419"/>
    <eLiterals name="V105" value="105" literal="420"/>
    <eLiterals name="V106" value="106" literal="500"/>
    <eLiterals name="V107" value="107" literal="501"/>
    <eLiterals name="V108" value="108" literal="502"/>
    <eLiterals name="V109" value="109" literal="503"/>
    <eLiterals name="V110" value="110" literal="504"/>
    <eLiterals name="V111" value="111" literal="505"/>
    <eLiterals name="V112" value="112" literal="506"/>
    <eLiterals name="V113" value="113" literal="507"/>
    <eLiterals name="V114" value="114" literal="508"/>
    <eLiterals name="V115" value="115" literal="509"/>
    <eLiterals name="V116" value="116" literal="510"/>
    <eLiterals name="V117" value="117" literal="511"/>
    <eLiterals name="V118" value="118" literal="512"/>
    <eLiterals name="V119" value="119" literal="513"/>
    <eLiterals name="V120" value="120" literal="514"/>
    <eLiterals name="V121" value="121" literal="515"/>
    <eLiterals name="V122" value="122" literal="516"/>
    <eLiterals name="V123" value="123" literal="517"/>
    <eLiterals name="V124" value="124" literal="518"/>
    <eLiterals name="V125" value="125" literal="519"/>
    <eLiterals name="V126" value="126" literal="520"/>
    <eLiterals name="V127" value="127" literal="600"/>
    <eLiterals name="V128" value="128" literal="601"/>
    <eLiterals name="V129" value="129" literal="602"/>
    <eLiterals name="V130" value="130" literal="603"/>
    <eLiterals name="V131" value="131" literal="604"/>
    <eLiterals name="V132" value="132" literal="605"/>
    <eLiterals name="V133" value="133" literal="606"/>
    <eLiterals name="V134" value="134" literal="607"/>
    <eLiterals name="V135" value="135" literal="608"/>
    <eLiterals name="V136" value="136" literal="609"/>
    <eLiterals name="V137" value="137" literal="610"/>
    <eLiterals name="V138" value="138" literal="611"/>
    <eLiterals name="V139" value="139" literal="612"/>
    <eLiterals name="V140" value="140" literal="613"/>
    <eLiterals name="V141" value="141" literal="614"/>
    <eLiterals name="V142" value="142" literal="615"/>
    <eLiterals name="V143" value="143" literal="616"/>
    <eLiterals name="V144" value="144" literal="617"/>
    <eLiterals name="V145" value="145" literal="618"/>
    <eLiterals name="V146" value="146" literal="619"/>
    <eLiterals name="V147" value="147" literal="620"/>
    <eLiterals name="V148" value="148" literal="700"/>
    <eLiterals name="V149" value="149" literal="701"/>
    <eLiterals name="V150" value="150" literal="702"/>
    <eLiterals name="V151" value="151" literal="703"/>
    <eLiterals name="V152" value="152" literal="704"/>
    <eLiterals name="V153" value="153" literal="705"/>
    <eLiterals name="V154" value="154" literal="706"/>
    <eLiterals name="V155" value="155" literal="707"/>
    <eLiterals name="V156" value="156" literal="708"/>
    <eLiterals name="V157" value="157" literal="709"/>
    <eLiterals name="V158" value="158" literal="710"/>
    <eLiterals name="V159" value="159" literal="711"/>
    <eLiterals name="V160" value="160" literal="712"/>
    <eLiterals name="V161" value="161" literal="713"/>
    <eLiterals name="V162" value="162" literal="714"/>
    <eLiterals name="V163" value="163" literal="715"/>
    <eLiterals name="V164" value="164" literal="716"/>
    <eLiterals name="V165" value="165" literal="717"/>
    <eLiterals name="V166" value="166" literal="718"/>
    <eLiterals name="V167" value="167" literal="719"/>
    <eLiterals name="V168" value="168" literal="720"/>
    <eLiterals name="V169" value="169" literal="800"/>
    <eLiterals name="V170" value="170" literal="801"/>
    <eLiterals name="V171" value="171" literal="802"/>
    <eLiterals name="V172" value="172" literal="803"/>
    <eLiterals name="V173" value="173" literal="804"/>
    <eLiterals name="V174" value="174" literal="805"/>
    <eLiterals name="V175" value="175" literal="806"/>
    <eLiterals name="V176" value="176" literal="807"/>
    <eLiterals name="V177" value="177" literal="808"/>
    <eLiterals name="V178" value="178" literal="809"/>
    <eLiterals name="V179" value="179" literal="810"/>
    <eLiterals name="V180" value="180" literal="811"/>
    <eLiterals name="V181" value="181" literal="812"/>
    <eLiterals name="V182" value="182" literal="813"/>
    <eLiterals name="V183" value="183" literal="814"/>
    <eLiterals name="V184" value="184" literal="815"/>
    <eLiterals name="V185" value="185" literal="816"/>
    <eLiterals name="V186" value="186" literal="817"/>
    <eLiterals name="V187" value="187" literal="818"/>
    <eLiterals name="V188" value="188" literal="819"/>
    <eLiterals name="V189" value="189" literal="820"/>
    <eLiterals name="V190" value="190" literal="900"/>
    <eLiterals name="V191" value="191" literal="901"/>
    <eLiterals name="V192" value="192" literal="902"/>
    <eLiterals name="V193" value="193" literal="903"/>
    <eLiterals name="V194" value="194" literal="904"/>
    <eLiterals name="V195" value="195" literal="905"/>
    <eLiterals name="V196" value="196" literal="906"/>
    <eLiterals name="V197" value="197" literal="907"/>
    <eLiterals name="V198" value="198" literal="908"/>
    <eLiterals name="V199" value="199" literal="909"/>
    <eLiterals name="V200" value="200" literal="910"/>
    <eLiterals name="V201" value="201" literal="911"/>
    <eLiterals name="V202" value="202" literal="912"/>
    <eLiterals name="V203" value="203" literal="913"/>
    <eLiterals name="V204" value="204" literal="914"/>
    <eLiterals name="V205" value="205" literal="915"/>
    <eLiterals name="V206" value="206" literal="916"/>
    <eLiterals name="V207" value="207" literal="917"/>
    <eLiterals name="V208" value="208" literal="918"/>
    <eLiterals name="V209" value="209" literal="919"/>
    <eLiterals name="V210" value="210" literal="920"/>
    <eLiterals name="V211" value="211" literal="1000"/>
    <eLiterals name="V212" value="212" literal="1001"/>
    <eLiterals name="V213" value="213" literal="1002"/>
    <eLiterals name="V214" value="214" literal="1003"/>
    <eLiterals name="V215" value="215" literal="1004"/>
    <eLiterals name="V216" value="216" literal="1005"/>
    <eLiterals name="V217" value="217" literal="1006"/>
    <eLiterals name="V218" value="218" literal="1007"/>
    <eLiterals name="V219" value="219" literal="1008"/>
    <eLiterals name="V220" value="220" literal="1009"/>
    <eLiterals name="V221" value="221" literal="1010"/>
    <eLiterals name="V222" value="222" literal="1011"/>
    <eLiterals name="V223" value="223" literal="1012"/>
    <eLiterals name="V224" value="224" literal="1013"/>
    <eLiterals name="V225" value="225" literal="1014"/>
    <eLiterals name="V226" value="226" literal="1015"/>
    <eLiterals name="V227" value="227" literal="1016"/>
    <eLiterals name="V228" value="228" literal="1017"/>
    <eLiterals name="V229" value="229" literal="1018"/>
    <eLiterals name="V230" value="230" literal="1019"/>
    <eLiterals name="V231" value="231" literal="1020"/>
    <eLiterals name="V232" value="232" literal="1100"/>
    <eLiterals name="V233" value="233" literal="1101"/>
    <eLiterals name="V234" value="234" literal="1102"/>
    <eLiterals name="V235" value="235" literal="1103"/>
    <eLiterals name="V236" value="236" literal="1104"/>
    <eLiterals name="V237" value="237" literal="1105"/>
    <eLiterals name="V238" value="238" literal="1106"/>
    <eLiterals name="V239" value="239" literal="1107"/>
    <eLiterals name="V240" value="240" literal="1108"/>
    <eLiterals name="V241" value="241" literal="1109"/>
    <eLiterals name="V242" value="242" literal="1110"/>
    <eLiterals name="V243" value="243" literal="1111"/>
    <eLiterals name="V244" value="244" literal="1112"/>
    <eLiterals name="V245" value="245" literal="1113"/>
    <eLiterals name="V246" value="246" literal="1114"/>
    <eLiterals name="V247" value="247" literal="1115"/>
    <eLiterals name="V248" value="248" literal="1116"/>
    <eLiterals name="V249" value="249" literal="1117"/>
    <eLiterals name="V250" value="250" literal="1118"/>
    <eLiterals name="V251" value="251" literal="1119"/>
    <eLiterals name="V252" value="252" literal="1120"/>
    <eLiterals name="V253" value="253" literal="1200"/>
    <eLiterals name="V254" value="254" literal="1201"/>
    <eLiterals name="V255" value="255" literal="1202"/>
    <eLiterals name="V256" value="256" literal="1203"/>
    <eLiterals name="V257" value="257" literal="1204"/>
    <eLiterals name="V258" value="258" literal="1205"/>
    <eLiterals name="V259" value="259" literal="1206"/>
    <eLiterals name="V260" value="260" literal="1207"/>
    <eLiterals name="V261" value="261" literal="1208"/>
    <eLiterals name="V262" value="262" literal="1209"/>
    <eLiterals name="V263" value="263" literal="1210"/>
    <eLiterals name="V264" value="264" literal="1211"/>
    <eLiterals name="V265" value="265" literal="1212"/>
    <eLiterals name="V266" value="266" literal="1213"/>
    <eLiterals name="V267" value="267" literal="1214"/>
    <eLiterals name="V268" value="268" literal="1215"/>
    <eLiterals name="V269" value="269" literal="1216"/>
    <eLiterals name="V270" value="270" literal="1217"/>
    <eLiterals name="V271" value="271" literal="1218"/>
    <eLiterals name="V272" value="272" literal="1219"/>
    <eLiterals name="V273" value="273" literal="1220"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSourceOptions">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="DataSourceOptions"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataTextField" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="dataTextField"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataValueField" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="dataValueField"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathToOptionsArray" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="pathToOptionsArray"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ClaimPath">
    <eLiterals name="V0" literal="'Sickness - indiv'"/>
    <eLiterals name="V1" value="1" literal="'Sickness - mult'"/>
    <eLiterals name="V2" value="2" literal="'Injury - indiv'"/>
    <eLiterals name="V3" value="3" literal="'Injury - mult'"/>
    <eLiterals name="V4" value="4" literal="'Death - indiv'"/>
    <eLiterals name="V5" value="5" literal="'Death - mult'"/>
    <eLiterals name="V6" value="6" literal="'Weather - either'"/>
    <eLiterals name="V7" value="7" literal="'Job Related - indiv'"/>
    <eLiterals name="V8" value="8" literal="'Job Related - mult'"/>
    <eLiterals name="V9" value="9" literal="'Other - indiv'"/>
    <eLiterals name="V10" value="10" literal="'Other - mult'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultipleAnswers">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="MultipleAnswers"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itemText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="itemText"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itemDateTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="itemDateTime"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itemInteger" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="itemInteger"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itemDecimal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="itemDecimal"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SortOptions">
    <eLiterals name="V0" literal="'A to Z'"/>
    <eLiterals name="V1" value="1" literal="'Z to A'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Data"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="registrant" eType="#//Registrant">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="registrant"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Registrant">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Registrant"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="first" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="first"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="last" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="last"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dietary_restrictions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="dietary_restrictions"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requires_lodging" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="requires_lodging"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emergency_contact_phone" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="emergency_contact_phone"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phone" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="phone"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="email"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requires_parking" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="requires_parking"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lodging_preference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="lodging_preference"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracks" upperBound="-1" eType="#//Tracks" eOpposite="#//Tracks/registrant">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="tracks"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="has_dietary_restrictions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="has_dietary_restrictions"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tracks">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Tracks"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="registrant" lowerBound="1" eType="#//Registrant" eOpposite="#//Registrant/tracks">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="registrant"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="name"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
