<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:com.corticon.rulesemf.canonicalvocabularymodel="http:///com/corticon/rulesemf/canonicalvocabularymodel.ecore" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="root" nsURI="http://root/1.0" nsPrefix="root">
  <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
    <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:RootExtension" majorVersionNumber="2" minorVersionNumber="1" buildNumber="8022" updateStamp="_LJdBFAF7Ee-XqsidxhJ5oQ" externalChecksum="2722078124:507989954" studioType="Javascript" customDataTypeDisplayCount="50">
      <languageCode>en_US</languageCode>
      <databaseAccess databasePropertyDisplayCount="50"/>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//coverageType">
        <dataTypeName manuallyCreated="true" value="coverageType"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration manuallyCreated="true" value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'Bodily Injury To Others'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Personal Injury Protection'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Bodily Injury Caused By An Uninsured Auto'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Damage To Someone Else’s Property'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Optional Bodily Injury To Others'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Medical Payments'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Collision'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Limited Collision'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Comprehensive'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Substitute Transportation'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Towing And Labor'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Bodily Injury Caused By An Underinsured Auto'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Comprehensive (Glass)'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//operatorClass">
        <dataTypeName manuallyCreated="true" value="operatorClass"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'10 Experienced Operator'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'15 Experienced Operator - age sixty-five or more'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'17 Inexperienced Principal Operator - licensed three or more years'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'18 Inexperienced Occasional Operator - licensed three or more years'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'20 Inexperienced Principal Operator'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'21 Inexperienced Occasional Operator'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'25 Inexperienced Principal Operator'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'26 Inexperienced Occasional Operator'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'30 Business Use'"/>
        </enumerationElements>
      </customDataTypeList>
      <vocabularyMappings name="JSON" ID="JSON" mappingType="JSON"/>
    </contents>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Coverage">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Coverage"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isCompulsary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="isCompulsary"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coverageType" eType="ecore:EEnum Vocabulary.ecore#//coverageType">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="Vocabulary.ecore#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.0">
          <name manuallyCreated="true" value="coverageType"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="basicLimitPerPerson" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="basicLimitPerPerson"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="basicLimitPerAccident" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="basicLimitPerAccident"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="increasedLimitAvailable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="increasedLimitAvailable"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="basicDeductible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="basicDeductible"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deductibleWaiverAvailable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="deductibleWaiverAvailable"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="application" lowerBound="1" eType="#//Application" eOpposite="#//Application/coverage">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="application"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endorsement" upperBound="-1" eType="#//Endorsement" eOpposite="#//Endorsement/coverage">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="endorsement"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deductible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="deductible"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="componentID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="componentID"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="policy" lowerBound="1" eType="#//Policy" eOpposite="#//Policy/coverage">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="policy"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="discount" upperBound="-1" eType="#//Discount" eOpposite="#//Discount/coverage">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="discount"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="driver" lowerBound="1" eType="#//Driver" eOpposite="#//Driver/coverage">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="driver"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="baseRate"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adjustmentFactor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="adjustmentFactor"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="coverageType">
    <eLiterals name="V0" literal="'Bodily Injury To Others'"/>
    <eLiterals name="V1" value="1" literal="'Personal Injury Protection'"/>
    <eLiterals name="V2" value="2" literal="'Bodily Injury Caused By An Uninsured Auto'"/>
    <eLiterals name="V3" value="3" literal="'Damage To Someone Else’s Property'"/>
    <eLiterals name="V4" value="4" literal="'Optional Bodily Injury To Others'"/>
    <eLiterals name="V5" value="5" literal="'Medical Payments'"/>
    <eLiterals name="V6" value="6" literal="'Collision'"/>
    <eLiterals name="V7" value="7" literal="'Limited Collision'"/>
    <eLiterals name="V8" value="8" literal="'Comprehensive'"/>
    <eLiterals name="V9" value="9" literal="'Substitute Transportation'"/>
    <eLiterals name="V10" value="10" literal="'Towing And Labor'"/>
    <eLiterals name="V11" value="11" literal="'Bodily Injury Caused By An Underinsured Auto'"/>
    <eLiterals name="V12" value="12" literal="'Comprehensive (Glass)'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Endorsement">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Endorsement"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="type"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverage" lowerBound="1" eType="#//Coverage" eOpposite="#//Coverage/endorsement">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="coverage"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="title"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="application" lowerBound="1" eType="#//Application" eOpposite="#//Application/endorsement">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="application"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Policy">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Policy"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate" eType="ecore:EDataType http:///com/corticon/rulesemf/canonicalvocabularymodel.ecore#//Date">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="startDate"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expirationDate" eType="ecore:EDataType http:///com/corticon/rulesemf/canonicalvocabularymodel.ecore#//Date">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="expirationDate"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paidInFull" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="paidInFull"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ageMonths" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="ageMonths"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOperators" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="numberOperators"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicle" upperBound="-1" eType="#//Vehicle" eOpposite="#//Vehicle/policy">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="vehicle"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="driver" upperBound="-1" eType="#//Driver" eOpposite="#//Driver/policy">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="driver"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverage" upperBound="-1" eType="#//Coverage" eOpposite="#//Coverage/policy">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="coverage"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="town" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="town"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Application">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Application"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="payInFull" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="payInFull"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverage" upperBound="-1" eType="#//Coverage" eOpposite="#//Coverage/application">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="coverage"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="driver" upperBound="-1" eType="#//Driver" eOpposite="#//Driver/application">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="driver"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicle" upperBound="-1" eType="#//Vehicle" eOpposite="#//Vehicle/application">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="vehicle"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="discount" upperBound="-1" eType="#//Discount" eOpposite="#//Discount/application">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="discount"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endorsement" upperBound="-1" eType="#//Endorsement" eOpposite="#//Endorsement/application">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="endorsement"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="town" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="town"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ratingTerritory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="ratingTerritory"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="county" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="county"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="townStatCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="townStatCode"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Driver">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Driver"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateOfBirth" eType="ecore:EDataType http:///com/corticon/rulesemf/canonicalvocabularymodel.ecore#//Date">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="dateOfBirth"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="residenceStreetAdress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="residenceStreetAdress"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="application" lowerBound="1" eType="#//Application" eOpposite="#//Application/driver">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="application"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yearsLicensed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="yearsLicensed"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yearLicensed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="yearLicensed"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operatorClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="operatorClass"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicle" upperBound="-1" eType="#//Vehicle" eOpposite="#//Vehicle/principalOperator">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="vehicle"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPrincipalOperator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="isPrincipalOperator"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operatorClassNo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="operatorClassNo"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="completedDriverTraining" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="completedDriverTraining"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="policy" lowerBound="1" eType="#//Policy" eOpposite="#//Policy/driver">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="policy"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="discount" upperBound="-1" eType="#//Discount" eOpposite="#//Discount/driver">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="discount"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAwayAtSchool" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="isAwayAtSchool"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAwayMilitary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="isAwayMilitary"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="baseRate"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="factor"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverage" upperBound="-1" eType="#//Coverage" eOpposite="#//Coverage/driver">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="coverage"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Discount">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Discount"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="type"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicle" lowerBound="1" eType="#//Vehicle" eOpposite="#//Vehicle/discount">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="vehicle"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="driver" lowerBound="1" eType="#//Driver" eOpposite="#//Driver/discount">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="driver"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="percent"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="application" lowerBound="1" eType="#//Application" eOpposite="#//Application/discount">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="application"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverage" lowerBound="1" eType="#//Coverage" eOpposite="#//Coverage/discount">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="coverage"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Vehicle"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="garageStreetAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="garageStreetAddress"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="automobileClassification" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="automobileClassification"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="application" lowerBound="1" eType="#//Application" eOpposite="#//Application/vehicle">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="application"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="make" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="make"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="model" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="model"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelYear" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="modelYear"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbolFactor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="symbolFactor"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ageYears" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="ageYears"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annualMileage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="annualMileage"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastInspectionDate" eType="ecore:EDataType http:///com/corticon/rulesemf/canonicalvocabularymodel.ecore#//Date">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="lastInspectionDate"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="principalOperator" lowerBound="1" eType="#//Driver" eOpposite="#//Driver/vehicle">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="principalOperator"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usedForBusiness" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="usedForBusiness"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="antiTheftDevice" upperBound="-1" eType="#//AntiTheftDevice">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="antiTheftDevice"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="policy" lowerBound="1" eType="#//Policy" eOpposite="#//Policy/vehicle">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="policy"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="discount" upperBound="-1" eType="#//Discount" eOpposite="#//Discount/vehicle">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AssociationEndExtension">
          <name manuallyCreated="true" value="discount"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="riskFactorID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="riskFactorID"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isElectricOrHybrid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="isElectricOrHybrid"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="operatorClass">
    <eLiterals name="V0" literal="'10 Experienced Operator'"/>
    <eLiterals name="V1" value="1" literal="'15 Experienced Operator - age sixty-five or more'"/>
    <eLiterals name="V2" value="2" literal="'17 Inexperienced Principal Operator - licensed three or more years'"/>
    <eLiterals name="V3" value="3" literal="'18 Inexperienced Occasional Operator - licensed three or more years'"/>
    <eLiterals name="V4" value="4" literal="'20 Inexperienced Principal Operator'"/>
    <eLiterals name="V5" value="5" literal="'21 Inexperienced Occasional Operator'"/>
    <eLiterals name="V6" value="6" literal="'25 Inexperienced Principal Operator'"/>
    <eLiterals name="V7" value="7" literal="'26 Inexperienced Occasional Operator'"/>
    <eLiterals name="V8" value="8" literal="'30 Business Use'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AntiTheftDevice">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="AntiTheftDevice"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="category"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="type"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccidentOrViolation">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="AccidentOrViolation"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateOfIncident" eType="ecore:EDataType http:///com/corticon/rulesemf/canonicalvocabularymodel.ecore#//Date">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="dateOfIncident"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="points" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="points"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="incidentType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="incidentType"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="atFault" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="atFault"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
